export const AjaxMethods = {
  GET: 'GET',
  DELETE: 'DELETE',
  HEAD: 'HEAD',
  OPTIONS: 'OPTIONS',
  POST: 'POST',
  PUT: 'PUT',
  PATCH: 'PATCH',
  GET_LOWER: 'get',
  DELETE_LOWER: 'delete',
  HEAD_LOWER: 'head',
  OPTIONS_LOWER: 'options',
  POST_LOWER: 'post',
  PUT_LOWER: 'put',
  PATCH_LOWER: 'patch',
  PURGE: 'PURGE',
  PURGE_LOWER: 'purge',
  LINK: 'LINK',
  LINK_LOWER: 'link',
  UNLINK: 'UNLINK',
  UNLINK_LOWER: 'unlink',
} as const
